# Generated by Django 5.2.8 on 2025-11-09 08:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
