# Generated by Django 5.2.8 on 2025-11-09 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_assignment_attachment_assignment_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionhistory',
            name='action',
            field=models.CharField(default='submitted', max_length=20),
        ),
    ]
