# Generated by Django 5.2.8 on 2025-11-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_submissionhistory_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionhistory',
            name='action',
            field=models.CharField(default='Submitted', max_length=20),
        ),
    ]
