# Generated by Django 5.2.8 on 2025-11-09 15:50

import django.db.models.deletion
import django.utils.timezone
import lms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0006_remove_quizquestion_quiz_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizattempt',
            options={'ordering': ['-submitted_at']},
        ),
        migrations.RenameField(
            model_name='quizattempt',
            old_name='completed_at',
            new_name='submitted_at',
        ),
        migrations.AlterUniqueTogether(
            name='quizattempt',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='question',
            name='correct_option',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_a',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_b',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_c',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_d',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='deadline',
        ),
        migrations.AddField(
            model_name='quiz',
            name='allow_multiple_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quiz',
            name='end_time',
            field=models.DateTimeField(default=lms.models.default_quiz_end_time),
        ),
        migrations.AddField(
            model_name='quiz',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='auto_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='lms.question')),
            ],
        ),
    ]
