# Generated by Django 5.2.8 on 2025-11-09 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0007_alter_quizattempt_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
